### ISSUE TITLE
Default Buttons

### ISSUE THREAD

**Issue by Conutant** [Conutant/TESSERACT#40] opened 2015-02-28 02:40 UTC
Buttons only change when in the customizer if I try to save the changes it goes back to primary and secondary.

**Comment by lunule** [comment] 2015-03-02 18:42
I can't reproduce this - if I define other buttons in the buttons section, it saves them without any problem.

At the same time I see the problem with the white button font color in case of outline button versions in the header - I'm working on this, will commit the fix tomorrow.

**Comment by Conutant** [comment] 2015-03-02 18:57
It is only when you first install the theme.  If you click on "Nothing" then go back to the button it will change but at first if you just change the button after you install the theme without click on "nothing
" first it will not work.

**Comment by Conutant** [comment] 2015-03-04 01:05
Ok seems to work down, did you change something or was it just me?  You can close this if you think it is solved also.

**Comment by Conutant** [comment] 2015-03-04 01:06
Theme is looking and feeling great!

**Comment by lunule** [comment] 2015-03-04 18:27
YEAH!!! I'm really happy to hear that! I mean both of your recent comments.

Concerning the "Nothing"-related issue - I'm not sure what happened here, I didn't change anything in the code of this section. Maybe it was caching related issue - yesterday I tried out the process you mentioned and still couldn't reproduce the saving problem.

Anyway - it's doesn't reoccur, so I close the issue.

**Closed as completed by lunule** 2015-03-04 18:27 UTC
